### ISSUE TITLE
PM.MGET has different return comparing with Redis MGET

### ISSUE THREAD

**Issue by chencheng1560** [memark-io/pmedis#14]
**Bug Description**
PM.MGET has different return comparing with Redis MGET

**Expected Behavior**
Same behavior as Redis MGET

**Steps to Reproduce**
1. pm.set foo bar
2. pm.sadd myset a
3. pm.sadd myset b
4. pm.mget foo myset

expected: bar (nil) 
in original redis, using mget command to a set suprisingly gets the return of (nil)
get: Executing test client: ERR KVDKHashModify.

**Comment by Mario-LuX** [comment]
solved by #35
