### ISSUE TITLE
PM.getex crashes the PMedis server

### ISSUE THREAD

**Issue by Mario-LuX** [memark-io/pmedis#18]
**Bug Description**

PM.getex command will crash the PMedis server

**Expected Behavior**
The same as original Redis

**Steps to Reproduce**

1. pm.getex

expected: wrong number of arguments
get: I/O error reading reply and then break down the redis server

**Comment by chencheng1560** [comment]
has been fixed by PR fix: fix command bug of PMedis string and list https://github.com/memark-io/pmedis/pull/20
