### ISSUE TITLE
PM.LPOP/PM.RPOP have different behavior from original Redis

### ISSUE THREAD

**Issue by Mario-LuX** [memark-io/pmedis#19]
**Bug Description**
PM.LPOP/PM.RPOP have different behavior from original Redis

**Expected Behavior**
The same behavior as original Redis

**Steps to Reproduce**

1. pm.lpop listcount -123 
   or
   pm.rpop listcount -123

expected: ERR value is out of range, must be positive
get: (nil)

**Comment by chencheng1560** [comment]
has been fixed by PR fix: fix command bug of PMedis string and list https://github.com/memark-io/pmedis/pull/20
