### ISSUE TITLE
Any two consecutive calls of PM.SUNION crashes the server

### ISSUE THREAD

**Issue by Mario-LuX** [memark-io/pmedis#33]
**Bug Description**
ANY two consecutive calls of SUNION crashes the server, no matter what arguments you use, they can be the same or totally different 

**Expected Behavior**
should return the result of sunion as original redis

**Steps to Reproduce**

1. pm.sadd set1 1 2 3
2. pm.sadd set2 2 3 4
3. pm.sadd set3 3 4 5
4. pm.sadd set4 4 5 6
5. pm.sunion set1 set2
6. pm.sunion set3 set4

**Comment by chencheng1560** [comment]
settled by PR #34
